name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/wine-quality.yml
      - projects/wine-quality/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to Dockerhub Container Registry
        uses: docker/login-action@master
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: ./projects/wine-quality
          file: ./projects/wine-quality/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USER }}/mlflow-project_wine-quality:latest
            docker.io/${{ secrets.DOCKERHUB_USER }}/mlflow-project_wine-quality:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
